name: Arduino CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.board.fqbn }}
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fqbn: arduino:mbed_nano:nanorp2040connect
          platforms: arduino:mbed_nano
          libraries: |
            # Install the libraries 
            - name: Servo
            - name: Arduino_LSM6DSOX
            - name: SensorFusion
          sketch-paths: |
            - ./
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Save sketches report as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: ${{ env.SKETCHES_REPORTS_PATH }}
          name: ${{ env.SKETCHES_REPORTS_PATH }}
  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@v1
        with:
          # The name of the workflow artifact created by the sketch compilation workflow
          sketches-reports-source: sketches-reports

